#!/usr/bin/env bash
# dependency-watch/run.sh — scan dependencies for known vulnerabilities.
#
# Detects the package manager(s) in use, runs the matching audit tool, formats
# results as Markdown to stdout. Optionally files a GitHub issue on high/critical
# findings (set DEPWATCH_FILE_ISSUE=1).
#
# Exit 0 always (this is a report; failures in subtools are noted but don't
# break the whole run).

set -uo pipefail  # NOTE: no -e

THRESHOLD="${DEPWATCH_THRESHOLD:-high}"
FILE_ISSUE="${DEPWATCH_FILE_ISSUE:-0}"
LABEL="${DEPWATCH_LABEL:-dependencies}"
TODAY=$(date '+%Y-%m-%d')

# Track whether we found anything at-or-above threshold (for optional issue creation).
HAS_FINDINGS=0

# --- Header ------------------------------------------------------------------

cat <<EOF
# Dependency Watch — $TODAY

Threshold for issue creation: \`$THRESHOLD\`

EOF

# --- Node / npm --------------------------------------------------------------

if [ -f "package.json" ]; then
  echo "## Node (npm)"
  echo
  if command -v npm >/dev/null 2>&1; then
    AUDIT=$(npm audit --json 2>/dev/null || echo "{}")

    if command -v jq >/dev/null 2>&1; then
      VULN=$(echo "$AUDIT" | jq '.metadata.vulnerabilities // {}')
      LOW=$(echo     "$VULN" | jq -r '.low      // 0')
      MOD=$(echo     "$VULN" | jq -r '.moderate // 0')
      HIGH=$(echo    "$VULN" | jq -r '.high     // 0')
      CRIT=$(echo    "$VULN" | jq -r '.critical // 0')

      echo "- Critical: **$CRIT**"
      echo "- High: **$HIGH**"
      echo "- Moderate: $MOD"
      echo "- Low: $LOW"
      echo

      if [ "$CRIT" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
        echo "<details><summary>Top findings</summary>"
        echo
        echo "\`\`\`"
        npm audit 2>/dev/null | head -40
        echo "\`\`\`"
        echo
        echo "</details>"
        echo
        HAS_FINDINGS=1
      fi
    else
      echo "_jq not installed — falling back to plain npm audit output._"
      echo
      echo "\`\`\`"
      npm audit 2>/dev/null | head -40
      echo "\`\`\`"
    fi
  else
    echo "_npm not installed — skipping._"
  fi
  echo
fi

# --- Python ------------------------------------------------------------------

if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ] || [ -f "Pipfile" ]; then
  echo "## Python"
  echo
  if command -v pip-audit >/dev/null 2>&1; then
    OUT=$(pip-audit 2>&1 || true)
    if echo "$OUT" | grep -q 'No known vulnerabilities found'; then
      echo "No known vulnerabilities."
    else
      echo "\`\`\`"
      echo "$OUT" | head -60
      echo "\`\`\`"
      HAS_FINDINGS=1
    fi
  else
    echo "_pip-audit not installed — \`pip install pip-audit\` to enable._"
  fi
  echo
fi

# --- Go ----------------------------------------------------------------------

if [ -f "go.mod" ]; then
  echo "## Go"
  echo
  if command -v govulncheck >/dev/null 2>&1; then
    OUT=$(govulncheck ./... 2>&1 || true)
    if echo "$OUT" | grep -q 'No vulnerabilities found'; then
      echo "No known vulnerabilities."
    else
      echo "\`\`\`"
      echo "$OUT" | head -80
      echo "\`\`\`"
      HAS_FINDINGS=1
    fi
  else
    echo "_govulncheck not installed — \`go install golang.org/x/vuln/cmd/govulncheck@latest\` to enable._"
  fi
  echo
fi

# --- Rust --------------------------------------------------------------------

if [ -f "Cargo.toml" ]; then
  echo "## Rust"
  echo
  if command -v cargo-audit >/dev/null 2>&1; then
    OUT=$(cargo audit 2>&1 || true)
    if echo "$OUT" | grep -q 'no vulnerable packages found'; then
      echo "No known vulnerabilities."
    else
      echo "\`\`\`"
      echo "$OUT" | head -60
      echo "\`\`\`"
      HAS_FINDINGS=1
    fi
  else
    echo "_cargo-audit not installed — \`cargo install cargo-audit\` to enable._"
  fi
  echo
fi

# --- Footer ------------------------------------------------------------------

echo "---"
echo
echo "_Generated by \`cron/dependency-watch/run.sh\` on $TODAY._"

# --- Optional: file a GitHub issue ------------------------------------------

if [ "$FILE_ISSUE" = "1" ] && [ "$HAS_FINDINGS" = "1" ]; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    echo
    echo "_Filing GitHub issue (DEPWATCH_FILE_ISSUE=1)..._" >&2
    # Re-run capture into a tempfile so we can pass it to gh issue create
    TMP=$(mktemp)
    "$0" > "$TMP" 2>/dev/null  # recursive call WITHOUT FILE_ISSUE to avoid loop
    DEPWATCH_FILE_ISSUE=0 gh issue create \
      --title "Dependency report — $TODAY" \
      --body-file "$TMP" \
      --label "$LABEL" >&2 || echo "_Failed to file issue._" >&2
    rm -f "$TMP"
  else
    echo "_Cannot file issue: gh CLI missing or unauthenticated._" >&2
  fi
fi

exit 0
